version: "3.7"

volumes:
    postgres_data_local: {}
    registry_file_store: {}

services:
    datapm-registry:
        image: "datapm/datapm-registry:${DATAPM_VERSION}"
        ports:
            - "4000:4000"
        env_file:
            - Docker-env
        depends_on:
            - "postgres"
            - "smtp"
        volumes:
            - type: volume
              source: registry_file_store
              target: /var/lib/datapm-registry/data
              consistency: cached
    postgres:
        image: postgres:13.3
        volumes:
            - type: volume
              source: postgres_data_local
              target: /var/lib/postgresql/data
              consistency: delegated
            - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_DB=datapm
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    smtp:
        image: namshi/smtp:latest
        environment:
            # This is ok, because the SMTP server is not exposed outside the docker network
            # 0.0.0.0/0 is used because the docker engine can assign any network
            - RELAY_NETWORKS=:0.0.0.0/0 